<a href="https://colab.research.google.com/github/pulkitgpt5/Python/blob/main/Array_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install numpy --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 74.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.6 which is incompatible.


In [8]:
import numpy as np

In [9]:
array_one=np.array([0,1,3,4,5,6,7])

In [10]:
array_one

array([0, 1, 3, 4, 5, 6, 7])

In [13]:
num=[11,12,32,12,45,64]
array_two=np.array(num)
array_two

array([11, 12, 32, 12, 45, 64])

In [15]:
array_of_zeros=np.zeros((2,3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
array_of_ones=np.ones((2,3))
array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
array_of_ones=np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
array_of_ones=np.ones((3,2),dtype=np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [21]:
array_of_empty=np.empty((3,2))
array_of_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
#NVI Function
array_eye=np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
array_of_even = np.arange(2,24,10)
array_of_even

array([ 2, 12, 22])

In [29]:
array_of_even = np.arange(2,4,0.5)
array_of_even

array([2. , 2.5, 3. , 3.5])

In [32]:
array_2D = np.array([(3,4,6),(2,1,6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [33]:
array_2D.shape

(2, 3)

In [35]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
array_nd=np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
# View the content of Array
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
print(x)

[0 1 2 3 4 5 6 7]


In [41]:
y=np.arange(8).reshape(2,4)
print(y)

[[0 1 2 3]
 [4 5 6 7]]


In [42]:
y=np.arange(16).reshape(4,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [43]:
y=np.arange(36).reshape(3,4,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [44]:
z=np.arange(10000)
print(z)

[   0    1    2 ... 9997 9998 9999]


In [49]:
import sys
np.set_printoptions(threshold=50)
print(np.arange(100).reshape(10,10))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]


In [50]:
fleet_mileage=np.array([14130,32746,76876])

In [51]:
fleet_mileage.sum()

np.int64(123752)

In [52]:
fleet_mileage.min()

np.int64(14130)

In [53]:
fleet_mileage.max()

np.int64(76876)

In [54]:
print("mean",fleet_mileage.mean())

mean 41250.666666666664


In [55]:
fleet_mileage.std()

np.float64(26312.381690417576)

In [59]:
num=np.arange(8).reshape(2,4)

In [60]:
num.sum()

np.int64(28)

In [61]:
num.min()

np.int64(0)

In [62]:
num.max()

np.int64(7)

In [63]:
num.sum(axis=0)

array([ 4,  6,  8, 10])

In [64]:
num

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
num.sum(axis=1)

array([ 6, 22])

In [69]:
num.mean()

np.float64(3.5)

In [70]:
#universal Function
np.sqrt(num)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [71]:
circli_radii= ([145,120,90,80,12])

In [72]:
circle_diamter= 2*circli_radii

In [73]:
circle_diamter

[145, 120, 90, 80, 12, 145, 120, 90, 80, 12]

In [74]:
np.sin(circle_diamter)

array([ 0.46774516,  0.58061118,  0.89399666, -0.99388865, -0.53657292,
        0.46774516,  0.58061118,  0.89399666, -0.99388865, -0.53657292])

In [75]:
np.cos(1)

np.float64(0.5403023058681398)

In [76]:
np.tan(45)

np.float64(1.6197751905438615)

In [82]:
np.exp(60)

np.float64(1.1420073898156842e+26)

In [84]:
np.median(circle_diamter)

np.float64(90.0)

In [91]:
x=np.arange(10)**3

In [92]:
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [93]:
x[3]

np.int64(27)

In [94]:
x[3:]

array([ 27,  64, 125, 216, 343, 512, 729])

In [95]:
x[-4]

np.int64(216)

In [96]:
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343])

In [98]:
x[3:-3]

array([ 27,  64, 125, 216])

In [99]:
x[3:]

array([ 27,  64, 125, 216, 343, 512, 729])

In [100]:
x[:10:2]

array([  0,   8,  64, 216, 512])

In [101]:
x[:3:2]

array([0, 8])

In [102]:
x[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [104]:
for i in x:
  print(i)

0
1
8
27
64
125
216
343
512
729


In [106]:
x=np.arange(8).reshape(2,4)

In [107]:
i=0
for i in x :
  print("row",i)

row [0 1 2 3]
row [4 5 6 7]


In [108]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [109]:
for data in x.flatten (order = 1):
  print(data)

TypeError: order must be str, not int

In [110]:
x=np.arange(16).reshape(4,4)

In [111]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
for i in np.nditer(x):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [117]:
for i in np.nditer(num,order="F",flags =['external_loop']):
  print(i)

[  0   1   8  27  64 125 216 343 512 729]


In [124]:
x.shape

(4, 4)

In [125]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
x.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [127]:
x.T.ravel()

array([ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15])

In [131]:
np.arange(18).reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [134]:
np.arange(18).reshape(6,-3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [135]:
x=np.ones_like(y)

In [136]:
x

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [142]:
p=np.arange(0,12)

In [143]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
np.split(p,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [145]:
np.split(p,[3,8])

[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [146]:
x1,x2=np.hsplit(p,2)

In [147]:
x1,x2

(array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11]))

In [148]:
!pip install scipy

NameError: name 'ndimage' is not defined